# -*- mode: conf -*-

FROM		webheroes/handler
MAINTAINER	Matthew Brisebois "matthew@webheroes.ca"

RUN		apt-get update #2015-03-26
RUN		pip install pytest psutil netifaces
RUN		pip install faker
RUN		pip install tabulate
